export const GET_TWEETS_TL_PENDING = "Home/GET_TWEETS_TL_PENDING";
export const GET_TWEETS_TL_SUCCESS = "Home/GET_TWEETS_TL_SUCCESS";
export const GET_TWEETS_TL_FAILURE = "Home/GET_TWEETS_TL_FAILURE";
